services:
  mysqldbs:
    image: mysql:8
    container_name: mysql-pro
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agrodbs
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - springboot-mysql-net

  backend:
    image: rishitha22/probackend:latest
    container_name: springboot
    ports:
      - "2025:2020"
    depends_on:
      - mysqldbs
    restart: on-failure
    networks:
      - springboot-mysql-net

  frontend:
    image: rishitha22/profrontend:latest
    container_name: reactpro
    ports:
      - "3000:85"
    depends_on:
      - backend
    restart: on-failure
    networks:
      - springboot-mysql-net

volumes:
  mysql_data:

networks:
  springboot-mysql-net:
